### ISSUE TITLE
Internal network unavailable

### ISSUE THREAD

**Issue by zhang1446802857** [sungaila/PDFtoZPL#36]
As the question requires, the method executed on the intranet yielded no results, and ultimately returned:

`Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.`

**Comment by sungaila** [comment]
Hi @zhang1446802857,

thanks for your feedback! Are you talking about the class library PDFtoZPL or the website [https://www.sungaila.de/PDFtoZPL/](https://www.sungaila.de/PDFtoZPL/)? I am not sure what you mean by "intranet" since this website is hosted on GitHub Pages.

If you are trying to host the website yourself, make sure to use ASP.NET Core, IIS or any other webserver for hosting. Simply opening `index.html` from your file system will not work.

**Comment by zhang1446802857** [comment]
I'm talking about the library PDFtoZPL.
My work place is a factory.So Intranet means. This network is only used inside the factory and does not allow access to the Internet.As a result, iis deployment fails to connect to devices inside the factory. So we installed the iis deployer on a fixed computer, but it always broke when we converted the zpl instructions
![image](https://github.com/sungaila/PDFtoZPL/assets/87363443/d543aecf-1d2e-4748-84d4-4333d4a6923a)

**Comment by sungaila** [comment]
Can you please log or print the exception message when `ConvertPdf` is called? When you call PDFtoZPL for the first time, the library pdfium.dll will be loaded once.

I believe that loading pdfium.dll went wrong and the error message `Failed to fetch.` just masks the real error message.

**Comment by zhang1446802857** [comment]
The exception message cannot be obtained, it seems that iis is interrupted. Just use the winform desktop program found to be normal, but the API program can not. I can't find the real problem at the moment.

**Comment by sungaila** [comment]
> Just use the winform desktop program found to be normal

So the library works in a desktop application, that's a good sign.

> I can't find the real problem at the moment.

Can you attach the debugger to the IIS web service? [Someone else had problems with IIS before](https://github.com/sungaila/PDFtoImage/pull/3) and I am wondering if your problem is related to that. IIS uses "shadow copies" for the application files and this might result in pdfium.dll not being found and IIS crashing.

Maybe you can print the exception message with something like this:
```csharp
try
{
	var zplCode = ConvertPdf(base64String, width: labelWidthDots, height: labelHeightDots);
}
catch (Exception ex)
{
	System.Diagnostics.Fail($"Exception message: {ex.Message}", ex.ToString());
}
```

**Comment by zhang1446802857** [comment]
Good morning. I tried your reply yesterday, but iis will stop running every time I execute here. I think it's because the computer is so bad. Ha ha, I'll see if I can find another way.
thank you for your help
