### ISSUE TITLE
label not correct postion 

### ISSUE THREAD

**Issue by Hussin22** [sungaila/PDFtoZPL#48]
### Question

``hello i try to counvert the pdf file : 

[png2pdf.pdf](https://github.com/sungaila/PDFtoZPL/files/14233075/png2pdf.pdf)

but when i make the below code : 

`
 string zpl = convert_pdfzpl(pdfBytes, 203, 799, 120, pageNumber);

private string convert_pdfzpl(byte[] pdfpage, int Dpi, int width, int height, int number_page)
{
    return Conversion.ConvertPdfPage(pdfpage, null, number_page, Dpi, width, height);

}

`
the printer print the label with content is not centerd and with a big margin in the left and this is not in pdf 

![IMG_20240211_171659](https://github.com/sungaila/PDFtoZPL/assets/76669327/2bf34564-729a-410c-aca7-60b7c0dc1b3a)

can you please support me to solve this issue

**Comment by michaelonz** [comment]
Hi- I have a similar issue and I suspect its because of the margins in the pdf - is it possible to have a flag to remove the margins (eg process the bitmap to find only the part that has pixels) - im trying to print the contents of a pdf that is printing to a smaller printer so i dont want the margins included in the image. 

This link has an autocrop function that would do the trick on the bitmap:
[(https://stackoverflow.com/questions/16775436/c-sharp-remove-bitmap-padding)]

**Comment by sungaila** [comment]
Hi @Hussin22, I am afraid I cannot help you here. Your PDF has no extra margins so the issue lays in your printer settings. You will have to adjust the printer settings to fit the label.

Hey @michaelonz, someone else wished for the ability to clip the PDF (https://github.com/sungaila/PDFtoImage/issues/63). This will be coming soonish.
